config/routes.rb
Rails.application.routes.draw do
  resources :tokens, path: :auth
  resources :body_parts, only: [:index, :update, :destroy]
  resources :users, only: [:new, :create]
  resources :affected_body_parts do
    resources :measuring_points
    resources :recordings
  end
  root to: "body_parts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affected_body_part.rb
class AffectedBodyPart < ApplicationRecord
  belongs_to :user
  belongs_to :body_part
  has_many :measuring_points, dependent: :destroy
  has_many :recordings, dependent: :destroy

  validates_uniqueness_of :body_part_id, scope: :user_id
  validates_presence_of :user_id
  validates_presence_of :body_part_id

  def name
    body_part.name
  end
end

app/controllers/affected_body_parts_controller.rb
class AffectedBodyPartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_affected_body_part, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /affected_body_parts
  # GET /affected_body_parts.json
  def index
    @affected_body_parts = @user.affected_body_parts
    @body_parts = BodyPart.all
  end

  # GET /affected_body_parts/1
  # GET /affected_body_parts/1.json
  def show
  end

  # GET /affected_body_parts/new
  def new
    @affected_body_part = AffectedBodyPart.new
  end

  # GET /affected_body_parts/1/edit
  def edit
  end

  # POST /affected_body_parts
  # POST /affected_body_parts.json
  def create
    @affected_body_part = @user.affected_body_parts.build(affected_body_part_params)

    respond_to do |format|
      if @affected_body_part.save
        format.html { redirect_to user_affected_body_parts_path(@user), notice: 'Affected body part was successfully created.' }
        format.json { render :show, status: :created, location: @affected_body_part }
      else
        format.html { render :new }
        format.json { render json: @affected_body_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affected_body_parts/1
  # PATCH/PUT /affected_body_parts/1.json
  def update
    respond_to do |format|
      if @affected_body_part.update(affected_body_part_params)
        format.html { redirect_to [@user, @affected_body_part], notice: 'Affected body part was successfully updated.' }
        format.json { render :show, status: :ok, location: @affected_body_part }
      else
        format.html { render :edit }
        format.json { render json: @affected_body_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affected_body_parts/1
  # DELETE /affected_body_parts/1.json
  def destroy
    @affected_body_part.destroy
    respond_to do |format|
      format.html { redirect_to affected_body_parts_url, notice: 'Affected body part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end
    def set_affected_body_part
      @affected_body_part = AffectedBodyPart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affected_body_part_params
      params.require(:affected_body_part).permit(:body_part_id)
    end
end

app/helpers/affected_body_parts_helper.rb
module AffectedBodyPartsHelper
end

app/views/affected_body_parts/_affected_body_part.html.erb
<div class="flex row card card-background">
  <h2><%= affected_body_part.body_part.name %></h2>
  <div class="flex column">
    <% if affected_body_part.measuring_points.any? %>
      <%= link_to "Start a recording", new_affected_body_part_recording_path(affected_body_part), class:"btn" %>
    <% end %>
    <%= link_to "Add measuring points", affected_body_part_measuring_points_path(affected_body_part), class:"btn" %>
  </div>
  <div>
  <% if affected_body_part.recordings.any? %>
    <h4>Recordings </h4>
    <ul>
    <% affected_body_part.recordings.each do |recording| %>
      <li><%= link_to recording.recorded_at, [affected_body_part, recording] %></li>
    <% end %>
    </ul>
    <% end %>
  </div>
</div>

app/views/affected_body_parts/_form.html.erb
<div class="form">
  <%= simple_form_for([@user, @affected_body_part]) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">

    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/affected_body_parts/edit.html.erb
<h1>Editing Affected Body Part</h1>

<%= render 'form', affected_body_part: @affected_body_part %>

<%= link_to 'Show', @affected_body_part %> |
<%= link_to 'Back', affected_body_parts_path %>

app/views/affected_body_parts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="heading">
  <h1>Track your measurements</h1>
</div>

<%= render @affected_body_parts %>

app/views/affected_body_parts/new.html.erb
<h1>New Affected Body Part</h1>

<%= render 'form', affected_body_part: @affected_body_part %>

app/views/affected_body_parts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_affected_body_part_path(@affected_body_part) %> |
<%= link_to 'Back', affected_body_parts_path %>